import 'package:flutter/material.dart';

class PetInfo {
  final String name;
  final String image;
  final String detailImage;
  final String description;
  final String tier;
  final String obtainingMethod;
  final String hatchChance;
  final String passive;
  final String obtainable;
  final String dateAdded;
  final String? box;
  final String? hunger;

  PetInfo({
    required this.name,
    required this.image,
    required this.detailImage,
    required this.description,
    required this.tier,
    required this.obtainingMethod,
    required this.hatchChance,
    required this.passive,
    required this.obtainable,
    required this.dateAdded,
    this.box,
    this.hunger,
  });
}

final List<PetInfo> pets = [
  PetInfo(
    name: 'Starfish',
    image: 'assets/starfish.jpg',
    detailImage: 'assets/starfish.jpg',
    description: 'A Starfish',
    tier: 'Common',
    obtainingMethod: 'Common Summer Egg',
    hatchChance: '50%',
    passive: 'You\'re a Star: Gains additional XP per second',
    obtainable: 'Yes',
    dateAdded: 'June 21, 2025',
  ),
  PetInfo(
    name: 'Queen Bee',
    image: 'assets/queen bee.png',
    detailImage: 'assets/queen bee.png',
    description: 'A Queen Bee',
    tier: 'Divine',
    obtainingMethod: 'Bee Egg',
    hatchChance: '25%',
    passive: 'Honey Maker: Produces honey over time',
    obtainable: 'Yes',
    dateAdded: 'June 15, 2025',
  ),
  PetInfo(
    name: 'Bunny',
    image: 'assets/bunny.png',
    detailImage: 'assets/bunny.png',
    description: 'The Bunny.',
    tier: 'Common',
    obtainingMethod: 'Common Egg',
    hatchChance: '33.33%',
    passive: 'Every 40s, eats a carrot at a 1.5x value bonus.',
    obtainable: 'Yes',
    dateAdded: 'May 3rd, 2025',
  ),
  PetInfo(
    name: 'Crab',
    image: 'assets/crab.png',
    detailImage: 'assets/crab.png',
    description: 'A Crab',
    tier: 'Common',
    obtainingMethod: 'Common Summer Egg',
    hatchChance: '25%',
    passive:
        'Pinch Pocket: Occasionally goes to another player and pinches them and grants you a small amount of sheckles',
    obtainable: 'Yes',
    dateAdded: 'June 21, 2025',
  ),
  PetInfo(
    name: 'Dog',
    image: 'assets/dog.png',
    detailImage: 'assets/dog.png',
    description: 'A loyal Dog',
    tier: 'Common',
    obtainingMethod: 'Common Egg',
    hatchChance: '33.33%',
    passive: 'Every 60s, 5% chance to dig up a random seed.',
    obtainable: 'Yes',
    dateAdded: 'May 3rd, 2025',
    box: 'Common Egg',
  ),
  PetInfo(
    name: 'Puppy',
    image: 'assets/dog1.png',
    detailImage: 'assets/dog1.png',
    description: 'A cute Puppy',
    tier: 'Common',
    obtainingMethod: 'Common Egg',
    hatchChance: '45%',
    passive: 'Playful: Makes you happy',
    obtainable: 'Yes',
    dateAdded: 'June 17, 2025',
  ),
  PetInfo(
    name: 'Seagull',
    image: 'assets/seagul.png',
    detailImage: 'assets/seagul.png',
    description: 'A Seagull',
    tier: 'Common',
    obtainingMethod: 'Common Summer Egg',
    hatchChance: '25%',
    passive:
        'Scavenger: Shoveling plants have a percent chance to drop the equivalent seed. Does not work on fruits. Hunger: 3500',
    obtainable: 'Yes',
    dateAdded: 'June 21, 2025',
  ),
  PetInfo(
    name: 'Bee',
    image: 'assets/bee.png',
    detailImage: 'assets/bee.png',
    description: 'The Bee',
    tier: 'Uncommon',
    obtainingMethod: 'Bee Egg',
    hatchChance: '65%',
    passive:
        'Every ~25m, flies to a nearby fruit and pollinates it, applying the Pollinated mutation.',
    obtainable: 'Yes',
    dateAdded: 'May 31, 2025',
    box: null,
    hunger: '25,000',
  ),
  PetInfo(
    name: 'Black Bunny',
    image: 'assets/black bunny.png',
    detailImage: 'assets/black bunny.png',
    description: 'The Black Bunny.',
    tier: 'Uncommon',
    obtainingMethod: 'Uncommon Egg',
    hatchChance: '25%',
    passive:
        'Every 40 seconds, the Black Bunny searches for a Carrot on the garden and eats it, automatically selling it at a marked up price of 1.5x value.',
    obtainable: 'Yes',
    dateAdded: 'May 3rd, 2025',
    box: null,
  ),
  PetInfo(
    name: 'Chicken',
    image: 'assets/chicken.png',
    detailImage: 'assets/chicken.png',
    description: 'The Chicken.',
    tier: 'Uncommon',
    obtainingMethod: 'Uncommon Egg',
    hatchChance: '25%',
    passive: 'Increases egg hatch speed by 10%.',
    obtainable: 'Yes',
    dateAdded: 'May 3rd, 2025',
    box: null,
  ),
  PetInfo(
    name: 'Cat',
    image: 'assets/moon cat.png',
    detailImage: 'assets/moon cat.png',
    description: 'The Cat.',
    tier: 'Uncommon',
    obtainingMethod: 'Uncommon Egg',
    hatchChance: '25%',
    passive:
        'Every 80 seconds, the Cat will nap for 10 seconds. New fruit within 10 studs will be 1.25x larger.',
    obtainable: 'Yes',
    dateAdded: 'May 3rd, 2025',
    box: null,
  ),
  PetInfo(
    name: 'Deer',
    image: 'assets/deer.png',
    detailImage: 'assets/deer.png',
    description: 'The Deer.',
    tier: 'Uncommon',
    obtainingMethod: 'Uncommon Egg',
    hatchChance: '25%',
    passive: 'Gives a 3% chance for berry plants to stay when harvested.',
    obtainable: 'Yes',
    dateAdded: 'May 3rd, 2025',
    box: null,
    hunger: '2,500',
  ),
  PetInfo(
    name: 'Monkey',
    image: 'assets/monkey.png',
    detailImage: 'assets/monkey.png',
    description: 'The Monkey.',
    tier: 'Rare',
    obtainingMethod: 'Rare Egg',
    hatchChance: '8.33%',
    passive:
        '~2.5% to refund fruit back to your inventory. Rarer plants have a lower chance to refund.',
    obtainable: 'Yes',
    dateAdded: 'May 3, 2025',
    box: null,
    hunger: '7,400',
  ),
  PetInfo(
    name: 'Orange Tabby',
    image: 'assets/orange tabby.png',
    detailImage: 'assets/orange tabby.png',
    description: 'The Orange Tabby.',
    tier: 'Rare',
    obtainingMethod: 'Rare Egg',
    hatchChance: '33.33%',
    passive:
        'Every 90 seconds, naps for 15 seconds and causes new fruit within 15 studs to grow 1.5x larger.',
    obtainable: 'Yes',
    dateAdded: 'May 3rd, 2025',
    box: null,
  ),
  PetInfo(
    name: 'Pig',
    image: 'assets/pig.png',
    detailImage: 'assets/pig.png',
    description: 'The Pig.',
    tier: 'Rare',
    obtainingMethod: 'Rare Egg',
    hatchChance: '16.67%',
    passive:
        'Every 118 seconds, the pig emits a 15 second aura that grants a 2x chance for plants within 15 studs to grow variant fruits.',
    obtainable: 'Yes',
    dateAdded: 'May 3rd, 2025',
    box: null,
  ),
  PetInfo(
    name: 'Rooster',
    image: 'assets/rooster.png',
    detailImage: 'assets/rooster.png',
    description: 'The Rooster.',
    tier: 'Rare',
    obtainingMethod: 'Rare Egg',
    hatchChance: '16.67%',
    passive: 'Increases egg hatch speed by ~20%.',
    obtainable: 'Yes',
    dateAdded: 'May 3rd, 2025',
    box: null,
  ),
  PetInfo(
    name: 'Spotted Deer',
    image: 'assets/spotted deer.png',
    detailImage: 'assets/spotted deer.png',
    description: 'The Spotted Deer.',
    tier: 'Rare',
    obtainingMethod: 'Rare Egg',
    hatchChance: '25%',
    passive: 'Gives a 5% chance for berry plants to stay when harvested.',
    obtainable: 'Yes',
    dateAdded: 'May 3rd, 2025',
    box: null,
    hunger: '2,500',
  ),
  PetInfo(
    name: 'Flamingo',
    image: 'assets/flamingo.png',
    detailImage: 'assets/flamingo.png',
    description: 'A Flamingo',
    tier: 'Rare',
    obtainingMethod: 'Rare Summer Egg',
    hatchChance: '30%',
    passive:
        'Flamboyance: Occasionally stands on one leg and all nearby plants will grow incredibly fast',
    obtainable: 'Yes',
    dateAdded: 'June 21, 2025',
    box: null,
  ),
  PetInfo(
    name: 'Toucan',
    image: 'assets/toucan.png',
    detailImage: 'assets/toucan.png',
    description: 'A Toucan',
    tier: 'Rare',
    obtainingMethod: 'Rare Summer Egg',
    hatchChance: '25%',
    passive:
        'Tropical Lover: Makes all nearby Tropical type plants have increased variant chance and grow bigger',
    obtainable: 'Yes',
    dateAdded: 'June 21, 2025',
    box: null,
  ),
  PetInfo(
    name: 'Sea Turtle',
    image: 'assets/sea turtle.png',
    detailImage: 'assets/sea turtle.png',
    description: 'A Sea Turtle',
    tier: 'Rare',
    obtainingMethod: 'Rare Summer Egg',
    hatchChance: '20%',
    passive:
        'Shell Share: Occasionally shares its wisdom to a random active pet granting bonus experience & Water Splash: Occasionally has a chance to Wet a nearby fruit',
    obtainable: 'Yes',
    dateAdded: 'June 21, 2025',
    box: null,
  ),
  PetInfo(
    name: 'Orangutan',
    image: 'assets/orangutan.png',
    detailImage: 'assets/orangutan.png',
    description: 'An Orangutan',
    tier: 'Rare',
    obtainingMethod: 'Rare Summer Egg',
    hatchChance: '15%',
    passive:
        'Helping Hands: When crafting, each material has a chance for it not to be consumed',
    obtainable: 'Yes',
    dateAdded: 'June 21, 2025',
    box: null,
  ),
  PetInfo(
    name: 'Seal',
    image: 'assets/seal.png',
    detailImage: 'assets/seal.png',
    description: 'A Seal',
    tier: 'Rare',
    obtainingMethod: 'Rare Summer Egg',
    hatchChance: '10%',
    passive:
        'Seal the Deal: When selling pets, has a 2.42% chance to get the pet back as its egg equivalent',
    obtainable: 'Yes',
    dateAdded: 'June 21, 2025',
    box: null,
    hunger: '17,000',
  ),
  PetInfo(
    name: 'Honey Bee',
    image: 'assets/honey bee.png',
    detailImage: 'assets/honey bee.png',
    description: 'The Honey Bee.',
    tier: 'Rare',
    obtainingMethod: 'Bee Egg',
    hatchChance: '25%',
    passive:
        'Every ~20m, flies to a nearby fruit and pollinates it, applying the Pollinated mutation. (The time is reduced when the pet is leveled up)',
    obtainable: 'Yes',
    dateAdded: 'May 31, 2025',
    box: null,
    hunger: '25,000',
  ),
  PetInfo(
    name: 'Wasp',
    image: 'assets/wasp.png',
    detailImage: 'assets/wasp.png',
    description: 'The Wasp.',
    tier: 'Rare',
    obtainingMethod: 'Anti Bee Egg',
    hatchChance: '55%',
    passive:
        'Every 30m, the Wasp flies to a nearby fruit and pollinates it, applying the Pollinated mutation. Every 10m, the Wasp stings a random pet and advances its ability cooldown by 60s.',
    obtainable: 'Yes',
    dateAdded: 'June 7th, 2025',
    box: null,
  ),
  PetInfo(
    name: 'Disco Bee',
    image: 'assets/disco bee.png',
    detailImage: 'assets/disco bee.png',
    description: 'The Disco Bee.',
    tier: 'Divine',
    obtainingMethod: 'Anti Bee Egg',
    hatchChance: '0.25%',
    passive: 'Every ~13m, ~22% chance a nearby fruit becomes Disco',
    obtainable: 'Yes',
    dateAdded: 'June 7th, 2025',
    box: null,
    hunger: '25,000',
  ),
  PetInfo(
    name: 'Raccoon',
    image: 'assets/raccoon.png',
    detailImage: 'assets/raccoon.png',
    description: 'The Raccoon.',
    tier: 'Divine',
    obtainingMethod: 'Night Egg',
    hatchChance: '0.1%',
    passive:
        'Every ~15 minutes, goes to another player\'s plot and steals (duplicate) a random crop and gives it to the player!',
    obtainable: 'Yes',
    dateAdded: 'May 10, 2025',
    box: null,
    hunger: '45,000',
  ),
  PetInfo(
    name: 'Dragonfly',
    image: 'assets/dragonfly.png',
    detailImage: 'assets/dragonfly.png',
    description: 'The Dragonfly.',
    tier: 'Divine',
    obtainingMethod: 'Bug Egg',
    hatchChance: '1%',
    passive: 'Transmutation: Every ~5 minutes, one random crop will turn gold.',
    obtainable: 'Yes',
    dateAdded: 'May 3, 2025',
    box: null,
    hunger: '100,000',
  ),
  PetInfo(
    name: 'Night Owl',
    image: 'assets/night owl.png',
    detailImage: 'assets/night owl.png',
    description: 'The Night Owl.',
    tier: 'Divine',
    obtainingMethod: 'Night Egg',
    hatchChance: '4%',
    passive: 'All active pets gain an additional <0.23 XP per second.',
    obtainable: 'Yes',
    dateAdded: 'May 10th, 2025',
    box: null,
    hunger: '50,000',
  ),
  PetInfo(
    name: 'Moth',
    image: 'assets/moth.png',
    detailImage: 'assets/moth.png',
    description: 'The Moth.',
    tier: 'Legendary',
    obtainingMethod: 'Anti Bee Egg',
    hatchChance: '13.75%',
    passive:
        'Silk song: Every ~13 minutes, restores 100% hunger of a random pet by singing to it',
    obtainable: 'Yes',
    dateAdded: 'June 7th, 2025',
  ),
  PetInfo(
    name: 'Capybara',
    image: 'assets/capybara.png',
    detailImage: 'assets/capybara.png',
    description: 'A Capybara',
    tier: 'Legendary',
    obtainingMethod: 'Paradise Egg',
    hatchChance: '21%',
    passive:
        'Chill Zone: All pets within 15.48 studs won`t lose hunger and will gain 3.48xp every second.',
    obtainable: 'Yes',
    dateAdded: 'June 21, 2025',
    hunger: '30000',
  ),
  PetInfo(
    name: 'Peacock',
    image: 'assets/peacock.png',
    detailImage: 'assets/peacock.png',
    description: 'The Peacock',
    tier: 'Legendary',
    obtainingMethod: 'Paradise Egg',
    hatchChance: '30%',
    passive:
        'Utter Beauty: Occasionally fans its feathers and all nearby pets will advance ability cooldowns',
    obtainable: 'Yes',
    dateAdded: 'June 21, 2025',
  ),
  PetInfo(
    name: 'Ostrich',
    image: 'assets/ostrich.png',
    detailImage: 'assets/ostrich.png',
    description: 'An Ostrich',
    tier: 'Legendary',
    obtainingMethod: 'Paradise Egg',
    hatchChance: '40%',
    passive: 'Eggsperience: Grants pets hatched from eggs an age bonus',
    obtainable: 'Yes',
    dateAdded: 'June 21, 2025',
  ),
  PetInfo(
    name: 'Scarlet Macaw',
    image: 'assets/scarlet macao.png',
    detailImage: 'assets/scarlet macao.png',
    description: 'A Scarlet Macaw',
    tier: 'Legendary',
    obtainingMethod: 'Paradise Egg',
    hatchChance: '8%',
    passive:
        'Verdant Bird: Every 12:00m, 16% chance to mutate a nearby fruit, applying the Verdant mutation.',
    obtainable: 'Yes',
    dateAdded: 'June 21, 2025',
    hunger: '12,000',
  ),
  PetInfo(
    name: 'Mole',
    image: 'assets/mole.png',
    detailImage: 'assets/mole.png',
    description: 'The Mole',
    tier: 'Legendary',
    obtainingMethod: 'Night Egg',
    hatchChance: '23.5%',
    passive:
        'Every ~80 seconds, digs down underground to find treasure. Can dig up gear or sheckles.',
    obtainable: 'Yes (Via Summer Harvest Event Rewards)',
    dateAdded: 'May 10th 2025',
  ),
  PetInfo(
    name: 'Frog',
    image: 'assets/frog.png',
    detailImage: 'assets/frog.png',
    description: 'The Frog.',
    tier: 'Legendary',
    obtainingMethod: 'Night Egg',
    hatchChance: '17.63%',
    passive:
        'Every >10 minutes, croaks and a random nearby Plant will advance growth by 24 hours.',
    obtainable: 'Yes',
    dateAdded: 'May, 10th, 2025',
  ),
  PetInfo(
    name: 'Moon Cat',
    image: 'assets/moon cat.png',
    detailImage: 'assets/moon cat.png',
    description: 'The Moon Cat',
    tier: 'Legendary',
    obtainingMethod: 'Summer Harvest',
    hatchChance: '',
    passive:
        'Moon Nap: Cat naps in a random spot in your farm, emitting an aura that boosts nearby fruit size.\nMoon Harvest: Grants a 0.06% chance for Night type plants to replant when harvested.',
    obtainable: 'Yes',
    dateAdded: 'May 24th 2025',
  ),
  PetInfo(
    name: 'Petal Bee',
    image: 'assets/petal bee.png',
    detailImage: 'assets/petal bee.png',
    description: 'The Petal Bee.',
    tier: 'Mythical',
    obtainingMethod: 'Bee Egg',
    hatchChance: '4%',
    passive:
        'Every ~25 minutes, it flies to a nearby fruit and pollinates it, applying Pollinated mutation. ~1% chance Flower type fruit stays after harvest.',
    obtainable: 'Yes',
    dateAdded: 'May 31, 2025',
  ),
  PetInfo(
    name: 'Turtle',
    image: 'assets/turtle.png',
    detailImage: 'assets/turtle.png',
    description: 'The Turtle.',
    tier: 'Legendary',
    obtainingMethod: 'Legendary Egg',
    hatchChance: '2.13%',
    passive: 'All sprinklers last ~20% longer.',
    obtainable: 'Yes',
    dateAdded: 'May 3rd, 2025',
  ),
  PetInfo(
    name: 'Tarantula Hawk',
    image: 'assets/tarantula.png',
    detailImage: 'assets/tarantula.png',
    description: 'The Tarantula Hawk.',
    tier: 'Legendary',
    obtainingMethod: 'Anti Bee Egg',
    hatchChance: '30%',
    passive:
        'Every 25m, the Tarantula Hawk flies to a nearby fruit and pollinates it, applying the Pollinated mutation.\nTarantula Stinger – Every 5m, the Tarantula Hawk stings a random pet and advances its ability cooldown by 80s.',
    obtainable: 'Yes',
    dateAdded: 'June 7th, 2025',
  ),
  PetInfo(
    name: 'Raptor',
    image: 'assets/raptor.png',
    detailImage: 'assets/raptor.png',
    description: 'The Raptor',
    tier: 'Legendary',
    obtainingMethod: 'Dinosaur Egg',
    hatchChance: '(35%)',
    passive:
        'Clever Claws: 2% – 2.5% chance fruit gets Amber mutation after collecting! Rarer plants have a lesser chance to mutate.\nRaptor Dance: Grants additional 14% – 14.5% increase to player movement speed!',
    obtainable: 'Yes',
    dateAdded: 'July 5th, 2025',
    hunger: '40,000',
  ),
  PetInfo(
    name: 'Brown Mouse',
    image: 'assets/brown mouse.png',
    detailImage: 'assets/brown mouse.png',
    description: 'The Brown Mouse.',
    tier: 'Mythical',
    obtainingMethod: 'Mythical Egg',
    hatchChance: '26.79%',
    passive:
        'Gains 750 bonus experience every 8 minutes. Increases the player\'s jump height by 12%.',
    obtainable: 'Yes',
    dateAdded: 'May 17th, 2025',
  ),
  PetInfo(
    name: 'Giant Ant',
    image: 'assets/giant ant.png',
    detailImage: 'assets/giant ant.png',
    description: 'The Giant Ant.',
    tier: 'Mythical',
    obtainingMethod: 'Bug Egg 25%\nExotic Bug Egg 30%',
    hatchChance: '',
    passive:
        '~10% chance for harvested crops to duplicate. Rarer fruits duplicate less often. ~5% extra chance for Candy type fruit to duplicate!',
    obtainable: 'Yes',
    dateAdded: 'May 3rd, 2025',
    hunger: '18,000',
  ),
  PetInfo(
    name: 'Grey Mouse',
    image: 'assets/grey mouse.png',
    detailImage: 'assets/grey mouse.png',
    description: 'The Grey Mouse.',
    tier: 'Mythical',
    obtainingMethod: 'Mythical Egg',
    hatchChance: '35.71%',
    passive:
        'Whisker Wisdom – Gains 500 bonus experience every 10 minutes. Increases the player\'s movement speed by 10% (Slightly increases as the player\'s pet(s) get(s) older).',
    obtainable: 'Yes',
    dateAdded: 'May 17th, 2025',
  ),
  PetInfo(
    name: 'Praying Mantis',
    image: 'assets/praying mantis.png',
    detailImage: 'assets/praying mantis.png',
    description: 'The Praying Mantis.',
    tier: 'Mythical',
    obtainingMethod: 'Bug Egg 4%\nExotic Bug Egg 4%',
    hatchChance: '',
    passive:
        'Zen zone: Every 80s, prays for 10.30s granting a 1.51x variant chance to crops within 10.30 studs.',
    obtainable: 'Yes',
    dateAdded: 'May 3rd, 2025',
  ),
  PetInfo(
    name: 'Red Giant Ant',
    image: 'assets/red giant ant.png',
    detailImage: 'assets/red giant ant.png',
    description: 'The Red Giant Ant.',
    tier: 'Mythical',
    obtainingMethod: 'Mythical Egg',
    hatchChance: '8.93%',
    passive:
        '5% chance harvested crops duplicate! Rarer crops have lower chance to duplicate. 5% extra chance for Fruit type crops to duplicate!',
    obtainable: 'Yes',
    dateAdded: 'May 17th, 2025',
  ),
  PetInfo(
    name: 'Snail',
    image: 'assets/snail.png',
    detailImage: 'assets/snail.png',
    description: 'The Snail.',
    tier: 'Mythical',
    obtainingMethod: 'Bug Egg 30%\nExotic Bug Egg 69%',
    hatchChance: '',
    passive:
        'Extra 5.08% chance harvested plants drop seeds. Rarer plants have a lower chance to duplicate',
    obtainable: 'Yes',
    dateAdded: 'May 3rd, 2025',
    hunger: '12,000',
  ),
  PetInfo(
    name: 'Squirrel',
    image: 'assets/squirrel.png',
    detailImage: 'assets/squirrel.png',
    description: 'The Squirrel.',
    tier: 'Mythical',
    obtainingMethod: 'Mythical Egg',
    hatchChance: '26.79%',
    passive:
        'Seed Stash: Small chance to not consume a use when using the Reclaimer. Gains additional XP per second.',
    obtainable: 'Yes',
    dateAdded: 'May 17th, 2025',
  ),
  PetInfo(
    name: 'Bear Bee',
    image: 'assets/bee bear.png',
    detailImage: 'assets/bee bear.png',
    description: 'The Bear Bee.',
    tier: 'Mythical',
    obtainingMethod: 'Bee Egg',
    hatchChance: '5%',
    passive: 'Wanna-bee: Every 25 minutes it mutates a crop to Honey Glazed',
    obtainable: 'Yes',
    dateAdded: 'May 31, 2025',
    hunger: '45,000',
  ),
  PetInfo(
    name: 'Butterfly',
    image: 'assets/butterfly.png',
    detailImage: 'assets/butterfly.png',
    description: 'Butterfly',
    tier: 'Mythical',
    obtainingMethod: 'Anti Bee Egg\nPremium Anti Bee Egg 149',
    hatchChance: '1%',
    passive:
        'Rainbow flutter: Every ~30m, flies to a nearby fruit with 5+ mutations, removes all mutations from it and turns it rainbow! Ignores favorited fruit.',
    obtainable: 'Yes',
    dateAdded: 'June, 2025',
    hunger: '26,000',
  ),
  PetInfo(
    name: 'Brontosaurus',
    image: 'assets/brontosaurus.png',
    detailImage: 'assets/brontosaurus.png',
    description: 'The Brontosaurus.',
    tier: 'Mythical',
    obtainingMethod: '',
    hatchChance: '1%',
    passive:
        'Giant Incubator: Pets hatched from eggs have 60% to get higher base weight',
    obtainable: 'Yes',
    dateAdded: 'July 5th, 2025',
    hunger: '85,000',
  ),
  PetInfo(
    name: 'Mimic Octopus',
    image: 'assets/mimic octopus.png',
    detailImage: 'assets/mimic octopus.png',
    description: 'A Mimic Octopus',
    tier: 'Mythical',
    obtainingMethod: 'Paradise Egg',
    hatchChance: '1%',
    passive:
        'Mimicry: Every 20m mimics and copies an ability from another pet and performs its ability! Does not copy pet mutation abilities.',
    obtainable: 'Yes',
    dateAdded: 'June 21, 2025',
  ),
];
